name: sistem_informasi_simpan_pinjam
version: 1.0.0+1
publish_to: none
description: Aplikasi Mobile dari Sistem Informasi Simpan Pinjam
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

font:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppons-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppons-Regular.ttf
      - asset: assets/fonts/Poppons-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppons-Medium.ttf
        weight: 500
