name: sistem_informasi_simpan_pinjam
version: 1.0.0+1
publish_to: none
description: Aplikasi Mobile dari Sistem Informasi Simpan Pinjam
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.9
  intl: ^0.18.1
  mime: ^1.0.4
  path_provider: ^2.0.5
  clipboard: ^0.1.3
  file_picker: ^4.0.0
  get: 4.6.5
  image_picker: ^0.8.6
  flutter_pdfview: ^1.0.2
  dropdown_button2: ^1.9.2
  http: ^0.13.5
  flutter: 
    sdk: flutter
  permission_handler: ^10.2.0
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

font:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppons-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppons-Regular.ttf
      - asset: assets/fonts/Poppons-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppons-Medium.ttf
        weight: 500
